
apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-pi-hist
  namespace: spark-ns
spec:
  type: Scala
  mode: cluster
  image: "akaliutau/spark-gcp:v3.1.3"
  imagePullPolicy: Always
  mainClass: org.apache.spark.examples.SparkPi
  mainApplicationFile: "local:///opt/spark/examples/jars/spark-examples_2.12-3.1.3.jar"
  arguments: ["30"]
  sparkVersion: "3.1.3"
  sparkConf:
    "spark.eventLog.enabled": "true"
    "spark.eventLog.dir": "gs://spark-history-server-logs-test"
    "spark.hadoop.fs.gs.project.id": "dev-k8s-playground"
    "spark.hadoop.google.cloud.auth.service.account.enable": "true"
    "spark.hadoop.google.cloud.auth.service.account.json.keyfile": "/etc/secrets/sparkonk8s.json"
    "spark.kubernetes.driver.secrets.history-secrets": "/etc/secrets"
    "spark.kubernetes.executor.secrets.history-secrets": "/etc/secrets"
  restartPolicy:
    type: Never
  volumes:
    - name: secret-volume
      secret:
        secretName: history-secrets
    - name: "test-volume"
      hostPath:
        path: "/tmp"
        type: Directory
  driver:
    terminationGracePeriodSeconds: 300
    cores: 1
    memory: "512m"
    labels:
      version: "3.1.3"
    serviceAccount: spo-release-spark
    volumeMounts:
      - name: driver-secret-volume
        readOnly: true
        mountPath: "/etc/secrets"
      - name: "test-volume"
        mountPath: "/tmp"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: "3.1.3"
    volumeMounts:
      - name: executor-secret-volume
        readOnly: true
        mountPath: "/etc/secrets"
      - name: "test-volume"
        mountPath: "/tmp"



